version: '3.8'

services:
  server:
    container_name: "app-server"
    build: .
    env_file:
      - ./.env
    ports:
      - "3082:3082"
    networks:
      - default
    command: "npm run dev"
    depends_on:
      - db
  db:
    container_name: "app-db"
    image: "postgres:latest"
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    networks:
      - default
networks:
  default:
volumes:
  postgres-data: {}